description = "Convert a Terrain50 file into an image"

[[arguments]]
name = "input"
description = "The input Terrain50 file"
# default_value = ""
type = "string"

[[arguments]]
name = "output"
description = "The output file to write to"
# default_value = ""
type = "string"

[[arguments]]
name = "stream"
description = "Treat the input as a stream of Terrain50 objects. The path specified by the --output argument will be a directory containing all the extracted objects, 1 image file per object."
default_value = false
type = "boolean"
