description = "Extract a slice from a larger stream of objects"

[[arguments]]
name = "input"
description = "The input file to extract a slice from (default: stdin)"
default_value = "-"
type = "string"

[[arguments]]
name = "output"
description = "The output file to write to (default: stdout)"
default_value = "-"
type = "string"

[[arguments]]
name = "count"
description = "The number of objects to extract (default: 1)"
default_value = 1
type = "integer"

[[arguments]]
name = "offset"
description = "The number of objects to skip before beginning extraction (default: 0)"
default_value = 0
type = "integer"
