description = "Read the Terrain50 file on stdin, validate it, and display any errors found"

[[arguments]]
name = "mode"
description = "The mode to operate in. Possible values: validate (default), stream. If stream, then validation will be done on individual items after parsing (otherwise validation is done during parsing, which catches more errors)"
default_value = "validate"
type = "string"

[[arguments]]
name = "quiet"
description = "Don't print validation individual success messages, only errors"
default_value = false
type = "boolean"
